index:
    path: /
    controller: App\Controller\DemoController::index

test:
  path: /test/{age<\d+>?0}
  controller: App\Controller\TestController::test
  methods: [GET, POST]
  host: localhost
  schemes: [https,http]

somme:
  path: /somme/{a}/{b}
  controller: App\Controller\SommeController::somme